#!/bin/bash

set -e

source /usr/libexec/s2i/env

if [ "$DEV_MODE" == true ] ; then
	set -x
fi

echo "---> Installing amster config"
cp -Rfp /tmp/src/. ./
chmod 0755 ./amster/*.sh

echo "---> Installing FRAM Instance"
mkdir -p ./instance

echo "---> Fix permissions on app-root"
fix-permissions /opt/app-root